version: '2'


networks:
  proxy:
    external: true

services:

  biercounter-app-h2:
    image: uportal/biercounter:latest
    labels:
      - "traefik.backend=bier-h2"
      - "traefik.frontend.rule=Host:bier-h2.united-portal.com"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.enable=true"

    restart: always
    networks:
      - proxy
    environment:
      APP_NAME: Mitarbeiter DB mit Spring Boot and H2
      ACTIVE_PROFILES: dev,h2
      APP_URL: https://bier-h2.united-portal.com

